In [1]:
using LinearAlgebra

In [2]:
v1 = [2,2,-1]; v2 = [-1,2,2];
q1 = v1/norm(v1)

3-element Vector{Float64}:
  0.6666666666666666
  0.6666666666666666
 -0.3333333333333333

In [3]:
q2 = v2/norm(v2)

3-element Vector{Float64}:
 -0.3333333333333333
  0.6666666666666666
  0.6666666666666666

In [4]:
Q = [q1 q2];
Q' * Q

2×2 Matrix{Float64}:
  1.0          -1.54198e-17
 -1.54198e-17   1.0

In [5]:
Q * Q'

3×3 Matrix{Float64}:
  0.555556  0.222222  -0.444444
  0.222222  0.888889   0.222222
 -0.444444  0.222222   0.555556

In [7]:
D = [0 11;1 7;2 27;3 31];
x = D[:,1];
y = D[:,2];

In [8]:
A = [ones(size(x)) x x.^2];
c = inv(A'*A)*(A'*y)

3-element Vector{Float64}:
 9.0
 2.0
 1.9999999999999858

In [9]:
D = [168 20 0 57;174 19 1 75;175 19 1 74;155 23 0 46;160 22 0 49];
h = D[:,1]; a = D[:,2]; g = D[:,3]; w = D[:,4];

In [10]:
A = [ones(size(h)) h a g];
c = inv(A'*A)*(A'*w)

4-element Vector{Float64}:
 384.99999999441206
  -0.9999999999854481
  -7.999999999941792
  16.0

In [18]:
L = [-4 -22;0 4;4 42]

3×2 Matrix{Int64}:
 -4  -22
  0    4
  4   42

In [19]:
x = L[:,1]

3-element Vector{Int64}:
 -4
  0
  4

In [21]:
y = L[:,2]

3-element Vector{Int64}:
 -22
   4
  42

In [22]:
A = [ones(size(x)) x];
c = inv(A'*A)*(A'*y)

2-element Vector{Float64}:
 8.0
 8.0

In [23]:
v1 = [3,0,1,0,2,-3];
v2 = [3,-2,1,0,3,0];
v3 = [3,0,5,-4,1,0];

In [25]:
dot(v1,v2)

16

In [26]:
u2 = v2 - (dot(v1,v2)/dot(v1,v1))*v1

6-element Vector{Float64}:
  0.9130434782608696
 -2.0
  0.30434782608695654
  0.0
  1.608695652173913
  2.0869565217391304

In [27]:
dot(v1,v3)

16

In [28]:
dot(u2,v3)

5.869565217391305

In [29]:
dot(u2,u2)

11.869565217391305

In [31]:
u3 = v3-(dot(u2,v3)/dot(u2,u2))*u2-(dot(v1,v3)/dot(v1,v1))*v1

6-element Vector{Float64}:
  0.4615384615384617
  0.989010989010989
  4.153846153846153
 -4.0
 -1.1868131868131868
  1.054945054945055